In [1]:
from sim.healthcare import *
import numpy as np
from sim.inputs import load_inputs
import pandas as pd


In [2]:
seed = 1167
year0 = 2000
poc_txi = 0.95

ss = {
    'Baseline': None,
    'TSwab': lambda pp: get_intv_tswab(pp),
    'POC': lambda pp: get_intv_poc(pp, target=0.8, p_txi_poc=poc_txi),
    'POC_Hi': lambda pp: get_intv_poc(pp, target=0.95, p_txi_poc=None)
}

In [3]:
inp = load_inputs('pars')

In [16]:
post = pd.read_csv('out/post_dy/Post.csv')
post = [dict(row) for i, row in post.iterrows()]
pars = inp.Cascade.prepare_pars(post[5], extra_sys=ss)

In [17]:
np.array([v.TruePos for v in pars['sys_Baseline']['sys'].seek_care(1, 0).values()]) / p_ent

array([0.79720353, 0.47452937, 1.17610727])

In [18]:
pars['p_dx']

array([0.79720353, 0.56973625, 0.55987668])

In [19]:
p_ent = pars['p_ent']
p_itt = pars['p_itt1']
p_pdx = pars['p_dx']
p_txi = pars['p_txi']

p_ent.sum(), (p_ent * p_itt).sum(), (p_ent * p_itt * p_pdx).sum(), (p_ent * p_itt * p_pdx * p_txi).sum()

(1.0, 0.26878638003, 0.18428642323494532, 0.15511739526232265)

In [34]:
pars['p_dx']

array([0.38940722, 0.22187427, 0.09269206])

In [39]:
pars['sys_Baseline']['sys'].Private.seek_care(1, 0).TruePos

0.60244836

In [33]:
ent = pars['sys_Baseline']['sys'].Public.Entry
for alg, p in zip(pars['sys_Baseline']['sys'].Public.Algorithms, ent):
    print(alg.dx(p, 0).TruePos)

0.17120129479511556
0.5121585756045581
0.03817644077404797
0.08468982663563399


In [ ]:
for i, pars in tqdm(enumerate(post)):
    p = obj.serve(pars)
    p = inp.Cas.prepare_pars(p, extra_sys=ss)

In [10]:
pars = post[0]
p = obj.serve(pars)
p = obj.Cas.prepare_pars(p, extra_sys=ss)

NameError: name 'obj' is not defined

In [10]:
intv = get_intv_poc(p0)

In [11]:
sys = get_system(p0)
test = sys.seek_care(1, 0)
[r.TruePos for r in test.values()]

[0.40988844456, 0.21915707549999996, 0.14476]

In [12]:
intv = get_intv_tswab(p0)
test = intv['sys'].seek_care(1, 0)
[r.TruePos for r in test.values()], intv['p_txi']

([0.41226846763200004, 0.21939437849999996, 0.14476], array([0.9, 0.8, 0.8]))

In [13]:
intv = get_intv_poc(p0, target=0.8, p_txi_poc = 0.95)
test = intv['sys'].seek_care(1, 0)
[r.TruePos for r in test.values()], intv['p_txi']

([0.425005224, 0.2709286799999999, 0.14476],
 array([0.94167386, 0.92595603, 0.8       ]))

In [14]:
intv = get_intv_poc(p0, target=0.95, p_txi_poc = None)
test = intv['sys'].seek_care(1, 0)
[r.TruePos for r in test.values()], intv['p_txi']

([0.4375557375, 0.2810140574999999, 0.14476], array([0.9, 0.8, 0.8]))